training_data = [
    {"text_input": "a person sitting in front of a laptop with coffee", "output": "When you pretend to be busy so your boss thinks you're working"},
    {"text_input": "a dog wearing sunglasses", "output": "Me trying to look cool but I'm just a mess"},
    {"text_input": "a cat staring out the window", "output": "That moment when you realize you have nothing planned for the weekend"},
    {"text_input": "a person playing video games", "output": "When the game freezes after hours of grinding"},
    {"text_input": "a street with people walking and shopping", "output": "When you walk past a store and hear 'SALE' but know you're broke"},
    {"text_input": "a group of friends laughing", "output": "When your friend says something dumb but you laugh anyway"},
    {"text_input": "a person holding a large pizza", "output": "Me trying to act healthy but pizza is life"},
    {"text_input": "a rainy day outside the window", "output": "When you want to go out but the rain is judging you"},
    {"text_input": "a pile of work on a desk", "output": "Me every Monday morning"},
    {"text_input": "someone jumping into a pool", "output": "That feeling when you finally get a break"},
    {"text_input": "two people fighting over the last slice of pizza", "output": "When you and your friend fight over the last snack"},
    {"text_input": "a person looking at their phone while on a train", "output": "When you're pretending to read but really stalking your ex"},
    {"text_input": "a dog playing fetch", "output": "When you throw the ball but it's too far and you regret everything"},
    {"text_input": "a group of people dancing", "output": "Me and my friends trying to dance but looking like fools"},
    {"text_input": "a person cleaning their room", "output": "That moment when you realize your 'clean' room is just a mess in disguise"},
    {"text_input": "a cat hiding under a blanket", "output": "When you're trying to avoid social interaction but people keep calling"},
    {"text_input": "a student taking a test", "output": "Me in every exam: Please let me remember something"},
    {"text_input": "a car with a flat tire", "output": "When life gives you lemons but you don't have time for that"},
    {"text_input": "someone enjoying ice cream on a hot day", "output": "Me on a summer day pretending I'm not sweating buckets"},
    {"text_input": "a person looking at a map", "output": "When you get lost in your own neighborhood"},
    {"text_input": "a child with a giant ice cream cone", "output": "That one time you were too excited for dessert"},
    {"text_input": "a person holding a bouquet of flowers", "output": "When you get flowers and pretend to appreciate them"},
    {"text_input": "a cat knocking something off a table", "output": "When you pretend to be graceful but you're a hot mess"},
    {"text_input": "a dog sleeping on a couch", "output": "Me after a long day: Do not disturb"},
    {"text_input": "a person trying to fold a fitted sheet", "output": "Me struggling to fold laundry like it's an Olympic sport"},
    {"text_input": "a crowded subway train", "output": "When you're too close to strangers and you just want to disappear"},
    {"text_input": "a person eating fast food", "output": "When you tell yourself you'll eat healthy but fast food wins every time"},
    {"text_input": "a bird perched on a tree branch", "output": "That feeling when you're trying to chill but life keeps interrupting"},
    {"text_input": "a person looking at their reflection in a mirror", "output": "When you see yourself after a 5-minute nap and regret it"},
    {"text_input": "a dog rolling in the grass", "output": "When you finally get a day off and just enjoy doing absolutely nothing"},
    {"text_input": "a person holding a giant book", "output": "When you pretend to read but actually just look at the pictures"},
    {"text_input": "a group of people taking a selfie", "output": "Me and my friends trying to take a picture but someone blinks every time"},
    {"text_input": "a person with a confused look", "output": "When you hear someone say 'I'll be there in 5 minutes' and you know they're lying"},
    {"text_input": "a person in front of a pile of clothes", "output": "That moment when you realize your wardrobe is a disaster"},
    {"text_input": "a dog jumping into water", "output": "When you dive into something without thinking and hope for the best"},
    {"text_input": "a person watching a movie with snacks", "output": "When you're at home alone with snacks and the best movie on"},
    {"text_input": "a person standing in front of a giant pizza", "output": "That moment when you question your life choices but pizza makes it better"},
    {"text_input": "a person in a messy kitchen", "output": "When cooking seemed like a good idea but now you regret it"},
    {"text_input": "a dog barking at a delivery truck", "output": "When your dog thinks they're the neighborhood guard dog"},
    {"text_input": "a couple looking at the sunset", "output": "When you pretend to be romantic but you're really just trying to get a good Instagram pic"},
    {"text_input": "a person holding a balloon", "output": "When you're happy but also lowkey worried about the balloon popping"},
    {"text_input": "a cat playing with a toy", "output": "When you're bored and the only entertainment is a toy mouse"},
    {"text_input": "a person sitting on a park bench", "output": "That feeling when you finally get a chance to just sit and do nothing"},
    {"text_input": "a dog with a hat", "output": "When you dress up your dog and they clearly hate it but you don't care"},
    {"text_input": "a person working out at the gym", "output": "When you think you're crushing it but you're actually dying inside"},
    {"text_input": "a person reading a book", "output": "When you're pretending to read but actually scrolling through memes"},
    {"text_input": "a person on a roller coaster", "output": "That moment when you realize you may have made a mistake but it's too late"},
    {"text_input": "a group of people eating at a restaurant", "output": "When the waiter says 'bon appétit' but you're just there for the free bread"},
    {"text_input": "someone jumping in excitement", "output": "When you finally get something you've wanted for so long"},
    {"text_input": "a dog sitting on a couch looking out the window", "output": "When you're judging people from the comfort of your own home"},
    {"text_input": "a group of friends eating snacks", "output": "When your friends bring snacks but you don't share"},
    {"text_input": "someone lying in a hammock", "output": "That moment when you realize your weekend is over and you did nothing"},
    {"text_input": "a person sitting in front of a laptop with coffee", "output": "When you pretend to be busy so your boss thinks you're working"},
    {"text_input": "a dog wearing sunglasses", "output": "Me trying to look cool but I'm just a mess"},
    {"text_input": "a cat staring out the window", "output": "That moment when you realize you have nothing planned for the weekend"},
    {"text_input": "a person playing video games", "output": "When the game finally freezes after hours of grinding"},
    {"text_input": "a street with people walking and shopping", "output": "When you walk past a store and hear 'SALE' but know you're broke"},
    {"text_input": "a group of friends laughing", "output": "When your friend says something dumb but you laugh anyway"},
    {"text_input": "a person holding a large pizza", "output": "Me trying to act healthy but pizza is life"},
    {"text_input": "a rainy day outside the window", "output": "When you want to go out but the rain is judging you"},
    {"text_input": "a pile of work on a desk", "output": "Me every Monday morning"},
    {"text_input": "someone jumping into a pool", "output": "That feeling when you finally get a break"},
    {"text_input": "two people fighting over the last slice of pizza", "output": "When you and your friend fight over the last snack"},
    {"text_input": "a person looking at their phone while on a train", "output": "When you're pretending to read but really stalking your ex"},
    {"text_input": "a dog playing fetch", "output": "When you throw the ball but it's too far and you regret everything"},
    {"text_input": "a group of people dancing", "output": "Me and my friends trying to dance but looking like fools"},
    {"text_input": "a person cleaning their room", "output": "That moment when you realize your 'clean' room is just a mess in disguise"},
    {"text_input": "a cat hiding under a blanket", "output": "When you're trying to avoid social interaction but people keep calling"},
    {"text_input": "a student taking a test", "output": "Me in every exam: Please let me remember something"},
    {"text_input": "a car with a flat tire", "output": "When life gives you lemons but you don't have time for that"},
    {"text_input": "someone enjoying ice cream on a hot day", "output": "Me on a summer day pretending I'm not sweating buckets"},
    {"text_input": "a person looking at a map", "output": "When you get lost in your own neighborhood"},
    {"text_input": "a child with a giant ice cream cone", "output": "That one time you were too excited for dessert"},
    {"text_input": "a person holding a bouquet of flowers", "output": "When you get flowers and pretend to appreciate them"},
    {"text_input": "a cat knocking something off a table", "output": "When you pretend to be graceful but you're a hot mess"},
    {"text_input": "a dog sleeping on a couch", "output": "Me after a long day: Do not disturb"},
    {"text_input": "a person trying to fold a fitted sheet", "output": "Me struggling to fold laundry like it's an Olympic sport"},
    {"text_input": "a crowded subway train", "output": "When you're too close to strangers and you just want to disappear"},
    {"text_input": "a person eating fast food", "output": "When you tell yourself you'll eat healthy but fast food wins every time"},
    {"text_input": "a bird perched on a tree branch", "output": "That feeling when you're trying to chill but life keeps interrupting"},
    {"text_input": "a person looking at their reflection in a mirror", "output": "When you see yourself after a 5-minute nap and regret it"},
    {"text_input": "a dog rolling in the grass", "output": "When you finally get a day off and just enjoy doing absolutely nothing"},
    {"text_input": "a person holding a giant book", "output": "When you pretend to read but actually just look at the pictures"},
    {"text_input": "a group of people taking a selfie", "output": "Me and my friends trying to take a picture but someone blinks every time"},
    {"text_input": "a person with a confused look", "output": "When you hear someone say 'I'll be there in 5 minutes' and you know they're lying"},
    {"text_input": "a person in front of a pile of clothes", "output": "That moment when you realize your wardrobe is a disaster"},
    {"text_input": "a dog jumping into water", "output": "When you dive into something without thinking and hope for the best"},
    {"text_input": "a person watching a movie with snacks", "output": "When you're at home alone with snacks and the best movie on"},
    {"text_input": "a person standing in front of a giant pizza", "output": "That moment when you question your life choices but pizza makes it better"},
    {"text_input": "a person in a messy kitchen", "output": "When cooking seemed like a good idea but now you regret it"},
    {"text_input": "a dog barking at a delivery truck", "output": "When your dog thinks they're the neighborhood guard dog"},
    {"text_input": "a couple looking at the sunset", "output": "When you pretend to be romantic but you're really just trying to get a good Instagram pic"},
    {"text_input": "a person holding a balloon", "output": "When you're happy but also lowkey worried about the balloon popping"},
    {"text_input": "a cat playing with a toy", "output": "When you're bored and the only entertainment is a toy mouse"},
    {"text_input": "a person sitting on a park bench", "output": "That feeling when you finally get a chance to just sit and do nothing"},
    {"text_input": "a dog with a hat", "output": "When you dress up your dog and they clearly hate it but you don't care"},
    {"text_input": "a person working out at the gym", "output": "When you think you're crushing it but you're actually dying inside"},
    {"text_input": "a person reading a book", "output": "When you're pretending to read but actually scrolling through memes"},
    {"text_input": "a person on a roller coaster", "output": "That moment when you realize you may have made a mistake but it's too late"},
    {"text_input": "a group of people eating at a restaurant", "output": "When the waiter says 'bon appétit' but you're just there for the free bread"},
    {"text_input": "someone jumping in excitement", "output": "When you finally get something you've wanted for so long"},
    {"text_input": "a dog sitting on a couch looking out the window", "output": "When you're judging people from the comfort of your own home"},
    {"text_input": "a group of friends eating snacks", "output": "When your friends bring snacks but you don't share"},
    {"text_input": "someone lying in a hammock", "output": "That moment when you realize your weekend is over and you did nothing"}
]
